# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(328, 488)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/hl-icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("#Form{border-image: url(:/bg/hl-bg.png);}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.display = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.display.setFont(font)
        self.display.setStyleSheet("border: 1px solid white;\n"
"border-radius: 10px;\n"
"background-color: #32012F;\n"
"color: rgb(255, 255, 255);")
        self.display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.display.setObjectName("display")
        self.gridLayout_2.addWidget(self.display, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.button_1 = QtWidgets.QPushButton(Form)
        self.button_1.setStyleSheet("    background-color: #260C1A;\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    border-radius: 35px;\n"
"    width: 70px;\n"
"    height: 70px;")
        self.button_1.setObjectName("button_1")
        self.gridLayout.addWidget(self.button_1, 4, 0, 1, 1)
        self.button_percentage = QtWidgets.QPushButton(Form)
        self.button_percentage.setStyleSheet("    background-color: #d4d4d2;\n"
"    color: black;\n"
"    font-size: 18px;\n"
"    border-radius: 35px;\n"
"    width: 70px;\n"
"    height: 70px;")
        self.button_percentage.setObjectName("button_percentage")
        self.gridLayout.addWidget(self.button_percentage, 1, 2, 1, 1)
        self.button_0 = QtWidgets.QPushButton(Form)
        self.button_0.setStyleSheet("    background-color: #260C1A;\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    border-radius: 35px;\n"
"    width: 70px;\n"
"    height: 70px;")
        self.button_0.setObjectName("button_0")
        self.gridLayout.addWidget(self.button_0, 5, 0, 1, 1)
        self.button_clear = QtWidgets.QPushButton(Form)
        self.button_clear.setStyleSheet("    background-color: #d4d4d2;\n"
"    color: black;\n"
"    font-size: 18px;\n"
"    border-radius: 35px;\n"
"    width: 70px;\n"
"    height: 70px;\n"
"    border: 1px valid")
        self.button_clear.setObjectName("button_clear")
        self.gridLayout.addWidget(self.button_clear, 1, 0, 1, 1)
        self.button_7 = QtWidgets.QPushButton(Form)
        self.button_7.setStyleSheet("    background-color: #260C1A;\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    border-radius: 35px;\n"
"    width: 70px;\n"
"    height: 70px;")
        self.button_7.setObjectName("button_7")
        self.gridLayout.addWidget(self.button_7, 2, 0, 1, 1)
        self.button_4 = QtWidgets.QPushButton(Form)
        self.button_4.setStyleSheet("background-color: #260C1A;\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    border-radius: 35px;\n"
"    width: 70px;\n"
"    height: 70px;")
        self.button_4.setObjectName("button_4")
        self.gridLayout.addWidget(self.button_4, 3, 0, 1, 1)
        self.button_plus_minus = QtWidgets.QPushButton(Form)
        self.button_plus_minus.setStyleSheet("    background-color: #d4d4d2;\n"
"    color: black;\n"
"    font-size: 18px;\n"
"    border-radius: 35px;\n"
"    width: 70px;\n"
"    height: 70px;")
        self.button_plus_minus.setObjectName("button_plus_minus")
        self.gridLayout.addWidget(self.button_plus_minus, 1, 1, 1, 1)
        self.button_divide = QtWidgets.QPushButton(Form)
        self.button_divide.setStyleSheet("    background-color: #F17105;\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    border-radius: 35px;\n"
"    width: 70px;\n"
"    height: 70px;")
        self.button_divide.setObjectName("button_divide")
        self.gridLayout.addWidget(self.button_divide, 1, 3, 1, 1)
        self.button_8 = QtWidgets.QPushButton(Form)
        self.button_8.setStyleSheet("    background-color: #260C1A;\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    border-radius: 35px;\n"
"    width: 70px;\n"
"    height: 70px;")
        self.button_8.setObjectName("button_8")
        self.gridLayout.addWidget(self.button_8, 2, 1, 1, 1)
        self.button_9 = QtWidgets.QPushButton(Form)
        self.button_9.setStyleSheet("background-color: #260C1A;\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    border-radius: 35px;\n"
"    width: 70px;\n"
"    height: 70px;")
        self.button_9.setObjectName("button_9")
        self.gridLayout.addWidget(self.button_9, 2, 2, 1, 1)
        self.button_multiply = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.button_multiply.setFont(font)
        self.button_multiply.setStyleSheet("    background-color: #F17105;\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    border-radius: 35px;\n"
"    width: 70px;\n"
"    height: 70px;")
        self.button_multiply.setObjectName("button_multiply")
        self.gridLayout.addWidget(self.button_multiply, 2, 3, 1, 1)
        self.button_5 = QtWidgets.QPushButton(Form)
        self.button_5.setStyleSheet("    background-color: #260C1A;\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    border-radius: 35px;\n"
"    width: 70px;\n"
"    height: 70px;")
        self.button_5.setObjectName("button_5")
        self.gridLayout.addWidget(self.button_5, 3, 1, 1, 1)
        self.button_6 = QtWidgets.QPushButton(Form)
        self.button_6.setStyleSheet("    background-color: #260C1A;\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    border-radius: 35px;\n"
"    width: 70px;\n"
"    height: 70px;")
        self.button_6.setObjectName("button_6")
        self.gridLayout.addWidget(self.button_6, 3, 2, 1, 1)
        self.button_subtract = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.button_subtract.setFont(font)
        self.button_subtract.setStyleSheet("    background-color: #F17105;\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    border-radius: 35px;\n"
"    width: 70px;\n"
"    height: 70px;")
        self.button_subtract.setObjectName("button_subtract")
        self.gridLayout.addWidget(self.button_subtract, 3, 3, 1, 1)
        self.button_2 = QtWidgets.QPushButton(Form)
        self.button_2.setStyleSheet("    background-color: #260C1A;\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    border-radius: 35px;\n"
"    width: 70px;\n"
"    height: 70px;")
        self.button_2.setObjectName("button_2")
        self.gridLayout.addWidget(self.button_2, 4, 1, 1, 1)
        self.button_3 = QtWidgets.QPushButton(Form)
        self.button_3.setStyleSheet("    background-color: #260C1A;\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    border-radius: 35px;\n"
"    width: 70px;\n"
"    height: 70px;")
        self.button_3.setObjectName("button_3")
        self.gridLayout.addWidget(self.button_3, 4, 2, 1, 1)
        self.button_add = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.button_add.setFont(font)
        self.button_add.setStyleSheet("    background-color: #F17105;\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    border-radius: 35px;\n"
"    width: 70px;\n"
"    height: 70px;")
        self.button_add.setObjectName("button_add")
        self.gridLayout.addWidget(self.button_add, 4, 3, 1, 1)
        self.button_dot = QtWidgets.QPushButton(Form)
        self.button_dot.setStyleSheet("    background-color: #260C1A;\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    border-radius: 35px;\n"
"    width: 70px;\n"
"    height: 70px;")
        self.button_dot.setObjectName("button_dot")
        self.gridLayout.addWidget(self.button_dot, 5, 2, 1, 1)
        self.button_equals = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.button_equals.setFont(font)
        self.button_equals.setStyleSheet("    background-color: #F17105;\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    border-radius: 35px;\n"
"    width: 70px;\n"
"    height: 70px;")
        self.button_equals.setObjectName("button_equals")
        self.gridLayout.addWidget(self.button_equals, 5, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculator"))
        self.display.setText(_translate("Form", "0"))
        self.button_1.setText(_translate("Form", "1"))
        self.button_percentage.setText(_translate("Form", "%"))
        self.button_0.setText(_translate("Form", "0"))
        self.button_clear.setText(_translate("Form", "C"))
        self.button_7.setText(_translate("Form", "7"))
        self.button_4.setText(_translate("Form", "4"))
        self.button_plus_minus.setText(_translate("Form", "+/-"))
        self.button_divide.setText(_translate("Form", "c"))
        self.button_8.setText(_translate("Form", "8"))
        self.button_9.setText(_translate("Form", "9"))
        self.button_multiply.setText(_translate("Form", "x"))
        self.button_5.setText(_translate("Form", "5"))
        self.button_6.setText(_translate("Form", "6"))
        self.button_subtract.setText(_translate("Form", "-"))
        self.button_2.setText(_translate("Form", "2"))
        self.button_3.setText(_translate("Form", "3"))
        self.button_add.setText(_translate("Form", "+"))
        self.button_dot.setText(_translate("Form", "."))
        self.button_equals.setText(_translate("Form", "="))
import calc3_rc
